//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursovaya.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kursovaya.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1625867651_5_kartinkin_com_p_oboi_minimalizm_nebo_krasivie_5 {
            get {
                object obj = ResourceManager.GetObject("1625867651_5-kartinkin-com-p-oboi-minimalizm-nebo-krasivie-5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1625867651_5_kartinkin_com_p_oboi_minimalizm_nebo_krasivie_51 {
            get {
                object obj = ResourceManager.GetObject("1625867651_5-kartinkin-com-p-oboi-minimalizm-nebo-krasivie-51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6Kqh6z_LK8ijMdUM9mFQTZ6jflyOR5rWTvdb6qpLN658ZqLgxAK_5pmXgm0CKqTSDt2_96639r536lJpBxcMo6T4 {
            get {
                object obj = ResourceManager.GetObject("6Kqh6z-LK8ijMdUM9mFQTZ6jflyOR5rWTvdb6qpLN658ZqLgxAK_5pmXgm0CKqTSDt2_96639r536lJpB" +
                        "xcMo6T4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6Kqh6z_LK8ijMdUM9mFQTZ6jflyOR5rWTvdb6qpLN658ZqLgxAK_5pmXgm0CKqTSDt2_96639r536lJpBxcMo6T41 {
            get {
                object obj = ResourceManager.GetObject("6Kqh6z-LK8ijMdUM9mFQTZ6jflyOR5rWTvdb6qpLN658ZqLgxAK_5pmXgm0CKqTSDt2_96639r536lJpB" +
                        "xcMo6T41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6Kqh6z_LK8ijMdUM9mFQTZ6jflyOR5rWTvdb6qpLN658ZqLgxAK_5pmXgm0CKqTSDt2_96639r536lJpBxcMo6T42 {
            get {
                object obj = ResourceManager.GetObject("6Kqh6z-LK8ijMdUM9mFQTZ6jflyOR5rWTvdb6qpLN658ZqLgxAK_5pmXgm0CKqTSDt2_96639r536lJpB" +
                        "xcMo6T42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6Kqh6z_LK8ijMdUM9mFQTZ6jflyOR5rWTvdb6qpLN658ZqLgxAK_5pmXgm0CKqTSDt2_96639r536lJpBxcMo6T43 {
            get {
                object obj = ResourceManager.GetObject("6Kqh6z-LK8ijMdUM9mFQTZ6jflyOR5rWTvdb6qpLN658ZqLgxAK_5pmXgm0CKqTSDt2_96639r536lJpB" +
                        "xcMo6T43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6Kqh6z_LK8ijMdUM9mFQTZ6jflyOR5rWTvdb6qpLN658ZqLgxAK_5pmXgm0CKqTSDt2_96639r536lJpBxcMo6T44 {
            get {
                object obj = ResourceManager.GetObject("6Kqh6z-LK8ijMdUM9mFQTZ6jflyOR5rWTvdb6qpLN658ZqLgxAK_5pmXgm0CKqTSDt2_96639r536lJpB" +
                        "xcMo6T44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AjRRm72rn3m6oAv6hlM49EeXchg2FMBzh2IH15FN1qAuQyo5eK4cJq9O4cOIrSJA95t2jCYcSRPRcx_K_oEZLJ9A {
            get {
                object obj = ResourceManager.GetObject("AjRRm72rn3m6oAv6hlM49EeXchg2FMBzh2IH15FN1qAuQyo5eK4cJq9O4cOIrSJA95t2jCYcSRPRcx-K-" +
                        "oEZLJ9A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BaYbGdp6GnT25hQOH1RU3wU9Xm_flhbaDX55sDjP6TpzjkxOzgYprRQq0x09fo1w85yOt9aVfsCD5tcNiUIdpx0C {
            get {
                object obj = ResourceManager.GetObject("BaYbGdp6GnT25hQOH1RU3wU9Xm_flhbaDX55sDjP6TpzjkxOzgYprRQq0x09fo1w85yOt9aVfsCD5tcNi" +
                        "UIdpx0C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap c8_OXBXqPpLZtNGradcx41y5gf6SuxHfdEHfDmfNHJ94KZvyckqpelDKEfNmrr_5gBozc1Zc5IfFeetrCZjNvsxr {
            get {
                object obj = ResourceManager.GetObject("c8-OXBXqPpLZtNGradcx41y5gf6SuxHfdEHfDmfNHJ94KZvyckqpelDKEfNmrr_5gBozc1Zc5IfFeetrC" +
                        "ZjNvsxr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap c8_OXBXqPpLZtNGradcx41y5gf6SuxHfdEHfDmfNHJ94KZvyckqpelDKEfNmrr_5gBozc1Zc5IfFeetrCZjNvsxr1 {
            get {
                object obj = ResourceManager.GetObject("c8-OXBXqPpLZtNGradcx41y5gf6SuxHfdEHfDmfNHJ94KZvyckqpelDKEfNmrr_5gBozc1Zc5IfFeetrC" +
                        "ZjNvsxr1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap c8_OXBXqPpLZtNGradcx41y5gf6SuxHfdEHfDmfNHJ94KZvyckqpelDKEfNmrr_5gBozc1Zc5IfFeetrCZjNvsxr2 {
            get {
                object obj = ResourceManager.GetObject("c8-OXBXqPpLZtNGradcx41y5gf6SuxHfdEHfDmfNHJ94KZvyckqpelDKEfNmrr_5gBozc1Zc5IfFeetrC" +
                        "ZjNvsxr2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dmOxA5gz580W3VrHl6oVrIif5lng_0kwTMTcToF2RIyrOjt40i_DjBjxiEXSy3bViRgfz8lVyLV6MtHvsruROhtQ {
            get {
                object obj = ResourceManager.GetObject("dmOxA5gz580W3VrHl6oVrIif5lng_0kwTMTcToF2RIyrOjt40i-DjBjxiEXSy3bViRgfz8lVyLV6MtHvs" +
                        "ruROhtQ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eraser_icon_icons_com_70168 {
            get {
                object obj = ResourceManager.GetObject("eraser_icon-icons.com_70168", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i {
            get {
                object obj = ResourceManager.GetObject("i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i1 {
            get {
                object obj = ResourceManager.GetObject("i1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minimalism_clouds_mountains_dark_1805093 {
            get {
                object obj = ResourceManager.GetObject("minimalism-clouds-mountains-dark-1805093", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minimalism_clouds_mountains_dark_18050931 {
            get {
                object obj = ResourceManager.GetObject("minimalism-clouds-mountains-dark-18050931", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oNd0dIZUoUOWWqtmbryLup7WQkAQ2GSXATLiUfx2_VQokPLrPISdkVBnbZHQpy7QxXAGYbbi5hVFv10UHhHYttW_ {
            get {
                object obj = ResourceManager.GetObject("oNd0dIZUoUOWWqtmbryLup7WQkAQ2GSXATLiUfx2-VQokPLrPISdkVBnbZHQpy7QxXAGYbbi5hVFv10UH" +
                        "hHYttW_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oNd0dIZUoUOWWqtmbryLup7WQkAQ2GSXATLiUfx2_VQokPLrPISdkVBnbZHQpy7QxXAGYbbi5hVFv10UHhHYttW_1 {
            get {
                object obj = ResourceManager.GetObject("oNd0dIZUoUOWWqtmbryLup7WQkAQ2GSXATLiUfx2-VQokPLrPISdkVBnbZHQpy7QxXAGYbbi5hVFv10UH" +
                        "hHYttW_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vtUKX8fBvFVVdHsO3q3c4w3zIO_y0hplKTS1N0zpHdKms0kN9epa07C1SofS25hBWGV_gobllQWnUb3Y1skAhvHF {
            get {
                object obj = ResourceManager.GetObject("vtUKX8fBvFVVdHsO3q3c4w3zIO-y0hplKTS1N0zpHdKms0kN9epa07C1SofS25hBWGV-gobllQWnUb3Y1" +
                        "skAhvHF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vtUKX8fBvFVVdHsO3q3c4w3zIO_y0hplKTS1N0zpHdKms0kN9epa07C1SofS25hBWGV_gobllQWnUb3Y1skAhvHF1 {
            get {
                object obj = ResourceManager.GetObject("vtUKX8fBvFVVdHsO3q3c4w3zIO-y0hplKTS1N0zpHdKms0kN9epa07C1SofS25hBWGV-gobllQWnUb3Y1" +
                        "skAhvHF1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Z53rYv86VFng39NEll5h3KTLRbM5JMu56phjBCAVKI5pX8WrU0m2NNzH9s8O7zd_nz6xkbHAEYu4AK30cb_QuZkV {
            get {
                object obj = ResourceManager.GetObject("Z53rYv86VFng39NEll5h3KTLRbM5JMu56phjBCAVKI5pX8WrU0m2NNzH9s8O7zd_nz6xkbHAEYu4AK30c" +
                        "b-QuZkV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Z53rYv86VFng39NEll5h3KTLRbM5JMu56phjBCAVKI5pX8WrU0m2NNzH9s8O7zd_nz6xkbHAEYu4AK30cb_QuZkV1 {
            get {
                object obj = ResourceManager.GetObject("Z53rYv86VFng39NEll5h3KTLRbM5JMu56phjBCAVKI5pX8WrU0m2NNzH9s8O7zd_nz6xkbHAEYu4AK30c" +
                        "b-QuZkV1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Z53rYv86VFng39NEll5h3KTLRbM5JMu56phjBCAVKI5pX8WrU0m2NNzH9s8O7zd_nz6xkbHAEYu4AK30cb_QuZkV2 {
            get {
                object obj = ResourceManager.GetObject("Z53rYv86VFng39NEll5h3KTLRbM5JMu56phjBCAVKI5pX8WrU0m2NNzH9s8O7zd_nz6xkbHAEYu4AK30c" +
                        "b-QuZkV2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Z53rYv86VFng39NEll5h3KTLRbM5JMu56phjBCAVKI5pX8WrU0m2NNzH9s8O7zd_nz6xkbHAEYu4AK30cb_QuZkV3 {
            get {
                object obj = ResourceManager.GetObject("Z53rYv86VFng39NEll5h3KTLRbM5JMu56phjBCAVKI5pX8WrU0m2NNzH9s8O7zd_nz6xkbHAEYu4AK30c" +
                        "b-QuZkV3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
